version: "3"

services:
  my_envoy_proxy:
    container_name: my-envoy-proxy
    command:
      - /bin/sh
      - -c
      - |
        sh ./scripts/setup_envoy_files
        /usr/local/bin/envoy -c          /tmp/envoy.yaml
    image: envoyproxy/envoy:v1.14.1
    healthcheck:
      test: pidof envoy || exit 1
      interval: 2s
      timeout: 3s
      retries: 4
    ports:
      - "${MYVAR_ENVOY_SERVICEPORT_SECURE}:${MYVAR_ENVOY_SERVICEPORT_SECURE}"
      - "${MYVAR_ENVOY_SERVICEPORT_INSECURE}:${MYVAR_ENVOY_SERVICEPORT_INSECURE}"
    network_mode: host
    volumes:
      - ./.env:/home/currency-reports/config/vars
      - ./envoy-proxy/envoy.tpl.yaml:/home/currency-reports/envoy-proxy/envoy.tpl.yaml
      - ./scripts:/home/currency-reports/scripts
      - ./ssl:/home/currency-reports/ssl
    working_dir: /home/currency-reports

  node_gen_protos:
    container_name: node-gen-protos
    command:
      - /bin/sh
      - -c
      - |
        rm -fR   ./gen-protos
        cp -R    ./gen-protos-copy   ./gen-protos
        cd       ./gen-protos
        npm ci
        npm run   clean-protos
        npm run   gen-protos-ts
        npm run   gen-protos-js
        npm run   copy-protos-to
        tail -f   /dev/null
    depends_on:
      my_envoy_proxy:
        condition: service_healthy
    environment:
      NODE_ENV: production
      TZ: UTC
    healthcheck:
      test: stat /home/currency-reports/proto-types/*.js || exit 1
      interval: 2s
      timeout: 3s
      retries: 4
    image: node:12.22.12-stretch
    volumes:
      - ./gen-protos:/home/currency-reports/gen-protos-copy
      - ./protos:/home/currency-reports/protos
      - ./proto-types:/home/currency-reports/proto-types
    working_dir: /home/currency-reports

  node_grpc_app:
    container_name: node-grpc-app
    build:
      context: .
      dockerfile: Dockerfile-node-grpc-app
    command:
      - /bin/sh
      - -c
      - |
        rm -fR   ./grpc
        cp -R    ./grpc-copy   ./grpc
        cd       ./grpc
        echo      ${GITHUB_AUTH_TOKEN} >> ./.npmrc
        npm set   unsafe-perm true
        npm ci    --only=production
        npm run   copy-protos-from
        npm run   start
    depends_on:
      node_gen_protos:
        condition: service_healthy
    environment:
      NODE_ENV: production
      TZ: UTC
    healthcheck:
      test: printf "GET / HTTP/1.0\r\n\r\n" | nc -v ${MYVAR_GRPC_SERVICEDOMAIN} ${MYVAR_GRPC_SERVERPORT}
      interval: 2s
      timeout: 3s
      retries: 4
    network_mode: host
    ports:
      - "${MYVAR_GRPC_SERVERPORT}:${MYVAR_GRPC_SERVERPORT}"
    volumes:
      - ./.env:/home/currency-reports/.env
      - ./grpc:/home/currency-reports/grpc-copy
      - ./protos:/home/currency-reports/protos
      - ./proto-types:/home/currency-reports/proto-types
    working_dir: /home/currency-reports

  node_web_apps:
    container_name: node-web-apps
    build:
      args:
        PROTOC_VER: ${PROTOC_VER}
        GRPCWEB_VER: ${GRPCWEB_VER}
      context: .
      dockerfile: Dockerfile-node-web-apps
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p ./config
        cp       ./.env              ./config/vars
        .        ./setup/enable_protoc
        rm -fR   ./web-client
        rm -fR   ./web-server
        cp -R    ./web-client-copy   ./web-client
        cp -R    ./web-server-copy   ./web-server
        cd        /home/currency-reports/web-client
        echo      ${GITHUB_AUTH_TOKEN} >> ./.npmrc
        npm set   unsafe-perm true
        npm ci    --only=production
        npm run   build
        npm run   build-worker --worker=indexedDb
        npm run   deploy-to-webserver
        cd        /home/currency-reports/web-server
        echo      ${GITHUB_AUTH_TOKEN} >> ./.npmrc
        npm ci    --only=production
        npm run   start
    depends_on:
      node_grpc_app:
        condition: service_healthy
    environment:
      NODE_ENV: production
      TZ: UTC
    network_mode: host
    ports:
      - "${MYVAR_WEB_SERVERPORT}:${MYVAR_WEB_SERVERPORT}"
    volumes:
      - ./protos:/home/currency-reports/protos
      - ./scripts:/home/currency-reports/scripts
      - ./setup:/home/currency-reports/setup
      - ./ssl:/home/currency-reports/ssl
      - ./web-client:/home/currency-reports/web-client-copy
      - ./web-server:/home/currency-reports/web-server-copy
      - ./.env:/home/currency-reports/.env
    working_dir: /home/currency-reports
